### ISSUE TITLE
Selecting CType 'text' shows CType 'uploads'

### ISSUE THREAD

**Issue by ruudsilvrants** [patrickbroens/TYPO3.ContentElements#4]
Change of a page content to text shows the field of page content uploads.
This occures in (currenty) tt_content line 366 
$GLOBALS['TCA']['tt_content']['types']['text']['showitem'] = '
has to be adjusted to:
$GLOBALS['TCA']['tt_content']['types']['textpic']['showitem'] = '

And line 399
$GLOBALS['TCA']['tt_content']['types']['text']['showitem'] = '
has to be adjusted to:
$GLOBALS['TCA']['tt_content']['types']['uploads']['showitem'] = '

Will try to make a commit this week ;)

**Comment by patrickbroens** [comment]
The content elements "text" and "textpic" have been replaced by "textmedia". Nevertheless you are right, the TCA declaration is wrong. I've already committed and pushed the stuff.

I'm going to write an update tool for migrating "text" and "textpic" to "textmedia" this week. In the meantime you can directly change this in the database by using the query "UPDATE tt_content SET CType='textmedia' WHERE CType IN ('text', 'textpic');"
